<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Department;

class DepartmentSeeder extends Seeder
{
    public function run(): void
    {
        Department::insert([
            [
                'hospital_id' => 1,
                'name' => 'General Medicine',
                'location' => 'Wing A • Room 102',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'Low Wait',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Pediatrics',
                'location' => 'Wing B • Room 205',
                'icon_type' => 'users',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'Moderate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Cardiology',
                'location' => 'Wing C • Room 310',
                'icon_type' => 'heart',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'Low Wait',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Dentistry & Dental Care',
                'location' => 'Wing D • Room 112',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'High Wait',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Dermatology',
                'location' => 'Wing A • Room 204',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'Low Wait',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Ophthalmology (Eye Clinic)',
                'location' => 'Wing B • Room 108',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'Moderate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Orthopedics',
                'location' => 'Wing C • Room 115',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'Moderate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'ENT (Ear, Nose & Throat)',
                'location' => 'Wing A • Room 301',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'Low Wait',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Obstetrics & Gynecology',
                'location' => 'Wing D • Room 220',
                'icon_type' => 'users',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'High Wait',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Neurology',
                'location' => 'Wing C • Room 402',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'Low Wait',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Psychiatry & Behavioral Health',
                'location' => 'Wing B • Room 305',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'Low Wait',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Urology',
                'location' => 'Wing A • Room 218',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'Moderate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Gastroenterology',
                'location' => 'Wing C • Room 201',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'Moderate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Endocrinology',
                'location' => 'Wing B • Room 114',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'Low Wait',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Physiotherapy & Rehab',
                'location' => 'Basement • Room B05',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'High Wait',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Radiology & X-Ray',
                'location' => 'Wing E • Room 101',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'High Wait',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Hematology & Blood Lab',
                'location' => 'Wing E • Room 105',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'High Wait',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Pulmonology (Respiratory)',
                'location' => 'Wing C • Room 305',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'Low Wait',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Oncology',
                'location' => 'Wing D • Room 401',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'Low Wait',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => 1,
                'name' => 'Nephrology (Kidney Care)',
                'location' => 'Wing A • Room 312',
                'icon_type' => 'user',
                'patients_ahead' => 0,
                'user_waitTime' => 0,
                'wait_status' => 'Moderate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}